/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoWorkerRouteImport } from './routes/demo-worker'
import { Route as IndexRouteImport } from './routes/index'

const DemoWorkerRoute = DemoWorkerRouteImport.update({
  id: '/demo-worker',
  path: '/demo-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-worker': typeof DemoWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-worker': typeof DemoWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-worker': typeof DemoWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo-worker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo-worker'
  id: '__root__' | '/' | '/demo-worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoWorkerRoute: typeof DemoWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-worker': {
      id: '/demo-worker'
      path: '/demo-worker'
      fullPath: '/demo-worker'
      preLoaderRoute: typeof DemoWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoWorkerRoute: DemoWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
